#!/bin/bash
# 南風網站部署修復輔助腳本

echo "🌿 南風心理輔導室 - 部署修復助手"
echo "================================"
echo ""
echo "此腳本幫助你修復 Vercel 和 GitHub Pages 部署問題"
echo ""
echo "📋 修復步驟："
echo ""
echo "【GitHub Pages 修復】"
echo "1. 打開: https://github.com/kenx1992-sudo/southwind-counselling/settings/pages"
echo "2. Branch: main, Folder: /website"
echo "3. 點 Save"
echo ""
echo "【Vercel 修復】"
echo "1. 打開: https://vercel.com/dashboard"
echo "2. 刪除舊專案或重新 Import"
echo "3. Root Directory 設為: website"
echo "4. 點 Deploy"
echo ""
echo "✅ 修復後驗證連結："
echo "- https://southwind-counselling.vercel.app/"
echo "- https://kenx1992-sudo.github.io/southwind-counselling/"
echo ""
echo "詳細指南見: DEPLOY_FIX_GUIDE.md"
